### ISSUE TITLE
Github based install does not work due to missing babel_config.js file

### ISSUE THREAD

**Issue by ghedsouza** [storybooks/react-storybook#626]
If you install `react-storybook` via the Github repo, instead of using npm directly, like so:
```
"devDependencies": {
    "@kadira/storybook": "git+https://github.com/storybooks/react-storybook.git"
  },
```
The resulting build, will not work because the `node_modules/\@kadira/storybook/dist/server/` directory does not contain the `babel_config.js` file referenced from [config.js](https://github.com/storybooks/react-storybook/blob/master/dist/server/config.js#L86).

# Steps to reproduce:
1. Clone https://github.com/ghedsouza/test-react-storybook-git-install
2. Go into repo directory and run `npm install`.
3. Run `./node_modules/.bin/build-storybook`

# Result
```
$ ./node_modules/.bin/build-storybook
module.js:327
    throw err;
    ^

Error: Cannot find module './babel_config'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/tmp/test-react-storybook-git-install/node_modules/@kadira/storybook/dist/server/config.js:86:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by ndelangen** [comment]
This will no longer be supported, since the dist folder will be removed from source-control.

If you do install from git, you're going to have to build the project locally.
