### ISSUE TITLE
Error: Cannot find module './WatchMissingNodeModulesPlugin'

### ISSUE THREAD

**Issue by danhoran** [storybooks/react-storybook#656]
Whenever I attempt to run storybook using `start-storybook -p 9001 -c .storybook` I receive the error: `Error: Cannot find module './WatchMissingNodeModulesPlugin'`.

```
Error: Cannot find module './WatchMissingNodeModulesPlugin'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<app>/node_modules/@kadira/storybook/dist/server/config/webpack.config.js:58:38)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
error Command failed with exit code 1.
```

Looking in the `./dist/server/config` directory I **cannot** see the requested file (`WatchMissingNodeModulesPlugin.js`) however I can see it in the `./src` directory.

I've tried running the scripts inside `./scripts` to regenerate the file but not having any luck.

**Comment by danhoran** [comment]
Turns out installing with `yarn` causes this to break.
