### ISSUE TITLE
Cannot load jpeg image via file-loader

### ISSUE THREAD

**Issue by rayshan** [storybooks/react-storybook#659]
Hi,

I moved `stories` directory under `app`, changed path in `.storybook/config.js` to `../app/stories`, put an image at `app/stories/demo.jpeg`, tried to load it in `app/stories/index.js` via `import imageUri from "./demo.jpeg";`, and got below error:

```
ERROR in ./app/stories/demo.jpeg
Module parse failed: /Users/rayshan/=Projects=/cartier/app/stories/demo.jpeg Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/rayshan/=Projects=/cartier/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/rayshan/=Projects=/cartier/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/rayshan/=Projects=/cartier/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/rayshan/=Projects=/cartier/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/rayshan/=Projects=/cartier/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./app/stories/index.js 21:12-34
```

It appears the path is correct, but `file-loader` isn't invoked. Help please?

**Comment by arunoda** [comment]
You may have introduced a custom webpack config. Then you need to use the file loader and configure it correctly.

It's hard for me to say something without looking at a sample repo.

**Comment by ndelangen** [comment]
If you need any further help, just re-open and give us some more details on how to reproduce, thanks!
