### ISSUE TITLE
Adding plugin to custom config throws compilation error

### ISSUE THREAD

**Issue by ericclemmons** [storybooks/react-storybook#676]
Within `.storybook/webpack.config.js`:

```js
  config.plugins.push(new webpack.EnvironmentPlugin([
    "API_URL",
    "NODE_ENV",
    "MIXPANEL_TOKEN",
  ]));
```

<details>
<summary><code>TypeError: callback is not a function at NullFactory.create</code></summary>
<blockquote>
TypeError: callback is not a function
    at NullFactory.create (/Users/Eric/Projects/HigherEducation/platform/node_modules/webpack/lib/NullFactory.js:9:9)
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:214:11
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/Eric/Projects/HigherEducation/platform/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/Eric/Projects/HigherEducation/platform/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:170:7)
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:320:12
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (native)
    at callback (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:140:10)
    at DependenciesBlock.<anonymous> (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/webpack/lib/NormalModule.js:115:10)
    at DependenciesBlock.onModuleBuild (/Users/Eric/Projects/HigherEducation/platform/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/Eric/Projects/HigherEducation/platform/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/Eric/Projects/HigherEducation/platform/node_modules/@kadira/storybook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/Eric/Projects/HigherEducation/platform/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
</blockquote>
</details>

I'm using:
```json
"@kadira/storybook": "2.35.3",
"webpack": "2.1.0-beta.22",
```

It's been an hour and I can't figure out why webpack would mess up because I'm simply adding another plugin...

**Comment by ericclemmons** [comment]
Ahah!   I didn't realize that `@kadira/storybook` _was using it's own `webpack` instead of the project one!_.

#651 would be the correct solution.

In the meantime, **anyone else with this problem can tell Storybook to use the webpack1 modules this way**:

```js
const webpack = require("@kadira/storybook/node_modules/webpack");
```
