### ISSUE TITLE
Crash on hot module replacement

### ISSUE THREAD

**Issue by jetpacmonkey** [storybooks/react-storybook#704]
I'm getting this traceback every time storybook's webpack instance tries to do HMR:

```
TypeError: moduleTemplate.render is not a function
    at /Users/jeremy/projects/web/node_modules/@kadira/storybook/node_modules/webpack/lib/Template.js:114:30
    at Array.forEach (native)
    at HotUpdateChunkTemplate.Template.renderChunkModules (/Users/jeremy/projects/web/node_modules/@kadira/storybook/node_modules/webpack/lib/Template.js:111:17)
    at HotUpdateChunkTemplate.render (/Users/jeremy/projects/web/node_modules/@kadira/storybook/node_modules/webpack/lib/HotUpdateChunkTemplate.js:15:27)
    at Compilation.<anonymous> (/Users/jeremy/projects/web/node_modules/webpack/lib/HotModuleReplacementPlugin.js:128:43)
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/jeremy/projects/web/node_modules/webpack/lib/HotModuleReplacementPlugin.js:111:36)
    at Compilation.applyPlugins (/Users/jeremy/projects/web/node_modules/tapable/lib/Tapable.js:26:37)
    at Compilation.<anonymous> (/Users/jeremy/projects/web/node_modules/@kadira/storybook/node_modules/webpack/lib/Compilation.js:558:8)
    at Compilation.applyPluginsAsync (/Users/jeremy/projects/web/node_modules/tapable/lib/Tapable.js:60:69)
```

This happens both when I update javascript and css files. I started seeing the behavior when I switched the bulk of my app over to webpack 2, so maybe something is conflicting there? The config for storybook is still be the same as it was before, as far as I'm aware, so that's my best guess...

A quick `console.log` of the webpack config I'm giving to storybook gives me the following:
```
{ stats: { colors: true, cached: false, cachedAssets: false },
  progress: true,
  resolve: { modulesDirectories: [ 'packages', 'node_modules' ] },
  module:
   { loaders:
      [ { test: /\.json$/, loader: 'json-loader' },
  { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff' },
  { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff' },
  { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'url-loader?limit=10000&mimetype=application/octet-stream' },
  { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file-loader' },
  { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
    loader: 'url-loader?limit=10000&mimetype=image/svg+xml' },
  { test: /\.(jpeg|jpg|png|gif)$/,
    loader: 'url-loader?limit=10240' },
  { test: /\.js$/,
    exclude: /node_modules/,
    loaders:
     [ 'babel-loader?{"presets":["react","es2015","stage-1"],"plugins":["transform-runtime","react-hot-loader/babel"],"env":{"production":{"plugins":["lodash"]},"test":{"sourceMaps":"inline","plugins":["istanbul"]}},"cacheDirectory":true}',
       'eslint-loader' ] },
  { test: /\.css$/,
    exclude: /node_modules\/rc-slider/,
    loaders:
     [ 'style-loader',
       'css-loader?{"sourceMap":true,"minimize":false,"modules":true,"localIdentName":"[name]__[local]___[hash:base64:5]","importLoaders":2}',
       'postcss-loader' ] },
  { test: /\.css/,
    include: /node_modules\/rc-slider/,
    loader: 'style!css' },
  { test: /\.svgicon$/,
    loader: 'svg-sprite-loader?{"spriteModule":"/Users/jeremy/projects/web/scripts/dev-sprite-module.js"}' } ] },
  plugins:
   [ HotModuleReplacementPlugin { multiStep: undefined, fullBuildTimeout: 200 },
     IgnorePlugin {
       resourceRegExp: /unicode\/category\/So/,
       contextRegExp: undefined },
     IgnorePlugin {
       resourceRegExp: /webpack-stats\.json$/,
       contextRegExp: undefined },
     IgnorePlugin { resourceRegExp: /^winston/, contextRegExp: undefined },
     DefinePlugin { definitions: {
        'process.env': {
          NODE_ENV: '"development"',
        },
      } } ],
  eslint: { emitWarning: true } }
```

**Comment by Toooy** [comment]
+1

**Comment by jetpacmonkey** [comment]
Alright, it's been almost a month with no response. But! I have good news! I just realized that I was pulling in my Webpack 2 plugins array from my main webpack config. So, the solution was to have just a little bit more duplicated config, but using storybook's internal version of webpack instead of my installed one:

```javascript
// We have bothered updating the namespace yet,
// so this line might be slightly different for you.
const webpack = require('@kadira/storybook/node_modules/webpack');

...

plugins: [
  webpack.HotModuleReplacementPlugin(),
  // etc...
]
```

**Comment by Toooy** [comment]
@jetpacmonkey  it works ?  Thx!  But I still don't know why...

**Comment by tmeasday** [comment]
Thanks for letting us know @jetpacmonkey

**Comment by numical** [comment]
@jetpacmonkey +1 Thanks!
